config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :problems do
    resources :solutions 
    resources :comments, :controller => "problem_comments"
  end

  resources :solutions do  
    resources :comments, :controller => "solution_comments"
  end

  resources :comments

  resources :media_contents, only: [:create]
  
  root :to => "pages#welcome"

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  title            :string(50)       default("")
#  content          :text
#  commentable_id   :integer
#  commentable_type :string
#  user_id          :integer
#  role             :string           default("comments")
#  created_at       :datetime
#  updated_at       :datetime
#  agree_level      :integer
#
# Indexes
#
#  index_comments_on_commentable_id    (commentable_id)
#  index_comments_on_commentable_type  (commentable_type)
#  index_comments_on_user_id           (user_id)
#

class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true, :counter_cache => true

  validates :content, presence: true

  default_scope -> { order('created_at ASC') }

   enum agree_level: { "agree" => 0,                       "object"           => 1,                       "against"   => 2,                      }



  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :login_required



  def edit
    @comment = current_user.comments.find(params[:id])
  end


  def update
    @comment = current_user.comments.find(params[:id])

    find_resource

    if @comment.update(comment_params)
      redirec_to problem_path(@resource)
    else
      render :edit
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    find_resource
    redirec_to problem_path(@resource)
  end

  protected



  def find_resource
    @resource = case @comment.commentable.class.to_s
    when "Problem"
      @comment.commentable
    else
      @comment.commentable.proble
    end
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div class="group ">


  
  <%= simple_form_for [@comment ] do |f| %>
  <%= f.input :content, :label => "Comment ( support Markdown syntax) ", :input_html => { :rows => 10, :data => { :provide => "markdown"} } %>
  <%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn pull-right" %>
  <% end %>
</div>

<div class='pull-left'>

   <%= ibutton('Delete This Comment', edit_comment_path(@comment), :class=>"btn btn-xs", :iclass => "icon icon-trash", :style => "font-weight: bold;background-color: #efefef; border-color: #e1e1e1; color:#cb7f7f;", :method => :delete, :data => { :confirm => "Are you sure?"}) %> 

</div>

app/views/comments/edit.html.erb
<div class="sr-page project-page">
  <h2 class="page-title">Edit Comment </h2>

  <div class="row">
    <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">

      <%= render "form" %>


    </div>
  </div>
</div>