config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :problems do
    resources :solutions 
    resources :comments, :controller => "problem_comments"
  end

  resources :solutions do  
    resources :comments, :controller => "solution_comments"
  end

  resources :comments

  resources :media_contents, only: [:create]
  
  root :to => "pages#welcome"

end

app/models/problem.rb
# == Schema Information
#
# Table name: problems
#
#  id              :integer          not null, primary key
#  title           :string
#  description     :text
#  causes          :text
#  user_id         :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  comments_count  :integer          default("0")
#  solutions_count :integer          default("0")
#

class Problem < ActiveRecord::Base

  belongs_to :user

  has_many :solutions


  acts_as_commentable
  
 
  def og_title
    ERB::Util.h("#{title}")
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :login_required

  def index
    @problems = Problem.all
  end


  def new
    @problem = Problem.new
  end

  def edit
    @problem = current_user.problems.find(params[:id])
  end

  def update
    @problem = current_user.problems.find(params[:id])

    if @problem.update(problem_params)
      redirect_to problem_path(@problem)
    else
      render :edit
    end
  end

  def create
    @problem = current_user.problems.build(problem_params)

    if @problem.save
      redirect_to problem_path(@problem)
    else
      render :new
    end
  end

  def show
    @problem = Problem.find(params[:id])
    @comment = Comment.new
    @solution_comment = Comment.new

    set_page_title @problem.og_title
  end


  protected


  def problem_params
    params.require(:problem).permit(:title,:description, :causes)
  end
end

app/helpers/problems_helper.rb
module ProblemsHelper

  def render_problem_author(problem)
    problem.user.email
  end

  def render_problem_title(problem)
    link_to(problem.title, problem_path(problem))
  end


  def render_problem_description(problem)
    problem.description.to_markdown
  end

  def render_problem_cause(problem)
    problem.causes.to_markdown
  end
end

app/views/problems/_comment_box.html.erb
<%= div_for(comment, class: "group problem-comment") do %>
<div class="media s-container">
  <a class="media-left" href="">
    <%= render_comment_avatar(comment.user, :small) %>
  </a>
  <div class="media-body">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="pull-right">
          <%= render_comment_edit_link(comment, current_user) %>
        </div>
        
        <div class="text-subhead-2"><%= render_user_name(comment.user) %> <span class="text-caption text-light">- <%= time_ago_in_words(comment.created_at) %></span></div>
        <p><%= render_comment_content(comment) %></p>
      </div>
      
    </div>
  </div>
</div>
<% end %>
<br>

app/views/problems/_comments.html.erb
<%# render :partial => "problems/comment_box", :collection => @problem.comments, :as => :comment %>  

app/views/problems/_form.html.erb
<%= simple_form_for @problem do |f|  %>

  <%= f.input :title %>

  <%= f.input :description , :input_html => { :rows => 10, :data => { :provide => "markdown"} } %>
  <%= f.input :causes , :input_html => { :rows => 10, :data => { :provide => "markdown"} } %>




  <%= f.button :submit, "Save", class: "btn btn-primary" %> or
  <%= link_to "Back", :back %>
<% end %>

app/views/problems/_list.html.erb
<div class="list-group-item group">

        <h4 class="text-subhead margin-none">
          <%= link_to(problem.title, problem_path(problem),  :class => "link-text-color")  %>
        </h4>
      
        <div class="pull-right">
            posted by
            <a href="#">
              <%= render_user_avatar(problem.user, :tiny) %>
              <%= render_user_name(problem.user) %> </a> &nbsp; | 
              <i class="fa fa-clock-o fa-fw"></i> <%= time_ago_in_words(problem.created_at) %> 


            <%= link_to problem_path(problem), :class => "btn btn-white text-light" do %>
               <i class="fa fa-comments fa-fw"></i> <%= problem.comments_count %>
            <% end %> 

        </div>
   

</div>

app/views/problems/_problem_comment_form.html.erb
<div class="group problem-comment-form">
 
<%= simple_form_for [@problem, Comment.new ] do |f| %>

  <%= f.input :content, :label => "Comment ( support Markdown syntax) ", :input_html => { :rows => 10, :data => { :provide => "markdown"} } %> 


  <%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn pull-right" %>
<% end %> 



</div>

app/views/problems/_problem_comments.html.erb
<div class="container">
  <div class="row">
    <div class="panel panel-default widget">
      <div class="panel-heading">
        <span class="glyphicon glyphicon-comment"></span>
        <h3 class="panel-title"> Recent Discussions </h3>
        <span class="label label-info"> <%= @problem.comments_count %> </span>
      </div>
        <div class="panel-body">
            <ul class="list-group">  
                <%= render :partial => "problems/comment_box", :collection => @problem.comments, :as => :comment %>  
            </ul>
    
        </div>
    </div>
  </div>
</div>

app/views/problems/_sidebar.html.erb
    <div class="col-md-4 col-lg-3">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="form-group form-control-material">
            <input id="forumSearch" type="text" class="form-control" placeholder="Type to search"><span class="ma-form-highlight"></span><span class="ma-form-bar"></span>
            <label for="forumSearch">Search ...</label>
          </div>
          <a href="#" class="btn btn-inverse paper-shadow relative" data-z="0.5" data-hover-z="1">Search</a>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">Categories</h4>
        </div>
        <ul class="list-group list-group-menu">
          <li class="list-group-item">
            <a href="website-blog.html"><i class="fa fa-chevron-right fa-fw"></i> All</a>
          </li>
          <li class="list-group-item">
            <a href="website-blog.html"><i class="fa fa-chevron-right fa-fw"></i> General</a>
          </li>
          <li class="list-group-item">
            <a href="website-blog.html"><i class="fa fa-chevron-right fa-fw"></i> Lessons</a>
          </li>
          <li class="list-group-item">
            <a href="website-blog.html"><i class="fa fa-chevron-right fa-fw"></i> Support</a>
          </li>
        </ul>
      </div>
    </div>

app/views/problems/_solution.html.erb
<div class="group">

  <div class="group">

    <%= render_user_avatar(solution.user, :small) %>   <%= render_user_name(solution.user) %> 
    <div class="pull-right">
      <%= render_solution_edit_link(solution, current_user) %>
    </div>
  </div>

  <div class="group">
    <h4> <%= render_solution_title(solution) %> </h4>
     <%= render_solution_content(solution) %>
  </div>
  <div class="pull-right">

    <i class="fa fa-clock-o fa-fw"></i> <%= time_ago_in_words(solution.created_at) %>
    <%= link_to("Leave comments", "#", :class => "underline") %>
  </div>     
  <div class="group">
    <br>
    <%= render :partial => "solutions/solution_comments", :locals => { :solution => solution } %>
    
  </div>
  
</div>

app/views/problems/_solutions.html.erb
<div class="page-section">
    <div class="row">
        <div class="col-md-12">
            <div class="pull-right">
                <%= ibutton("", new_problem_solution_path(@problem), :class => "btn btn-white btn-circle paper-shadow relative", :iclass => "fa fa-plus") %>
                
            </div>
            <h2 class="text-headline margin-none">Solutions</h2>
            <p class="text-subhead text-light">  <%= @problem.solutions_count %> solution(s)</p>
            <hr>
            <%= render :partial =>  "problems/solution", :collection => @problem.solutions.recent , as: :solution  %>
            
        </div>
    </div>
</div>

app/views/problems/edit.html.erb
<div class="sr-page project-page">
  <h2 class="page-title">Edit <%= @problem.title %> </h2>

  <div class="row">
    <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">

      <%= render "form" %>


    </div>
  </div>
</div>

app/views/problems/index.html.erb
<div class="page-section">
    <div class="row">
        <div class="col-md-8 col-lg-9">
                <div class="list-group">
                    <div class="list-group-item">
                       
                            <div class="pull-right">

                                <%= ibutton("Start Discussion", new_problem_path, :class => "btn btn-default btn-primary", :iclass => "fa fa-fw fa-plus") %>
                            </div>

                            <div class="media-body">
                                <h4 class="text-headline margin-none">General</h4>
                                <p class="text-subhead text-light"> General Topic </p>
                            </div>
                  
                    </div>
          
                    <%= render :partial => "problems/list", :collection => @problems , :as => :problem %>

                </div>
         
        </div>

    </div>
</div>

app/views/problems/new.html.erb
<div class="sr-page project-page">
  <h2 class="page-title">Start a problem discussion </h2>

  <div class="row">
    <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">

      <%= render "form" %>


    </div>
  </div>
</div>

app/views/problems/show.html.erb
<div class="page-section">
  <div class="row">
    <div class="col-md-8 col-lg-9">
      <div class="page-section padding-top-none">
        <div class="s-container">
          <h1 class="text-display-1 margin-top-none"><%= @problem.title %></h1>
          <div class="pull-right">
            <%= link_to("Edit", edit_problem_path(@problem), :class => "underline") %>
          </div>
          
          <p class="text-light text-caption">
            posted by
            <a href="#">
              <%= render_user_avatar(@problem.user, :tiny) %>
              <%= render_user_name(@problem.user) %>
            </a> &nbsp; | <i class="fa fa-clock-o fa-fw"></i> <%= time_ago_in_words(@problem.created_at) %>
          </p>
        </div>
        <div class="group">
          <h3> What's the problem? </h3>
          <%= render_problem_description(@problem) %>
        </div>
        <div class="group">
          <h3> Why it happens? </h3>
          <%= render_problem_cause(@problem) %>
        </div>
      </div>
      <%= render "solutions" %>
      <%= render "comments" %>
      <%# render :partial => "problems/problem_comment_form" %>
    </div>
    <%# render :partial => "sidebar" %>
  </div>
</div>