config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :problems do
    resources :solutions 
    resources :comments, :controller => "problem_comments"
  end

  resources :solutions do  
    resources :comments, :controller => "solution_comments"
  end

  resources :comments

  resources :media_contents, only: [:create]
  
  root :to => "pages#welcome"

end

app/views/common/_bootstrap_modal.html.erb
<div id="modal-from-dom" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modal-from-dom-label" aria-hidden="true">

</div>

app/views/common/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">ReleasePlan</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <%= render_list :class => "nav navbar-nav" do |li| 
        li << link_to("Problems", problems_path)
#        li << link_to("Changes",  "#" )
#        li << link_to("Releases", "#" )
      end %>

      <%= form_tag "/search" , :class => "navbar-form navbar-left", :method => :get do %>
        <div class="form-group">

        <input id="search-form" type="text" name="q" class="form-control" value="<%= params[:q] %>" placeholder="Search" />
    
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      <% end %>

      <ul class="nav navbar-nav navbar-right">

 

        <% if !current_user %>
        <li> <%= link_to("Login", new_user_session_path) %> </li>
        <% else %>



        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Hi!, <%= current_user.email %>  
            <b class="caret"></b>
          </a>


          <ul class="dropdown-menu">

            <li> <%= link_to("Start a discussion",  new_problem_path ) %> </li>
  


            <li> 
              <%= link_to("Logout", destroy_user_session_path, :method => :delete ) %>
            </li>

          </ul>
        </li>


        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>